### ISSUE TITLE
Clarify rate limits.

### ISSUE THREAD

**Issue by skorokithakis** [gmcquillan/django-brake#20]
Could you clarify here (or preferably in the docs) how the ratelimits work? If I specify 10/m and 100/h, when does it limit me? When does it let me back? Will I be de-limited after a minute even if I am making more requests?

**Comment by gmcquillan** [comment]
Good questions!

So the ratelimits are bucketized per function, per field value, per ip, and per time period, right? So what happens if you're over a ratelimit? The key for each ratelimit has a TTL that's the same as its period as defined by the bucket. 

Similarly, you can TTL out of shorter period time-buckets, while larger ones still block you, https://github.com/gmcquillan/django-brake/blob/master/brake/tests/tests.py#L242 which can be confusing until you use the utilities and check on cache values directly.

So if you hit a ratelimit and then manage to hit that endpoint with any of the criteria that match a ratelimit bucket, then you'll keep the full count until you stop doing that. So if you trip a 1 minute bucket, and then do one request a minute thereafter, you'll still be ratelimited. This seemed like the best tradeoff between complexity and secure defaults.

I'm open to making it more configurable, documenting, etc. Let me know how you'd like to change it.

**Comment by skorokithakis** [comment]
My problem is that, say, I have a ratelimit of 10/minute. If someone makes one request per 30 seconds, they'll be ratelimited after 5 minutes, even though they're way under the limit. Is this accurate?

I'd like to fix this use case first. About staying rate-limited, you mean when block=False, right?

**Comment by gmcquillan** [comment]
Right. I think that would be a problem here. 

The primary purpose of this library is to prevent automated password cracking, and denial of service attacks; this is why it errs on the side of blocking people. It's probably not the most suitable choice for managing internal API ratelimits, say. IP addresses among other things remain the same and it just doesn't handle edge cases in granularity very well.

It sounds like you want to use a windowing function to get very precise counts for hits within a time range. Unfortunately, memcache doesn't lend itself to that kind of query, since you have to know which keys you're querying for in advance. What you could do instead, I suppose, is encode more of the time data in the value you're storing.

But you'd still run into TTL problems eventually.

**Comment by skorokithakis** [comment]
Not really, you could get pretty close to it by just not refreshing the expiration time. That way, "ten requests a minute" would count forwards from the first one, not backwards from the last. Someone making two requests a minute would never be rate limited.

I'll have a PR for you tomorrow and we can discuss the rest then, hopefully it'll only be two or three more lines.
